name: 'Update notion cards'
description: 'Javascript action for updating notion cards'
author: 'Ramy Loveridge'
branding:
  icon: 'align-justify'
  color: 'blue'
inputs:
  page_property:
    description: 'The name of the property to update. Default is "Status"'
    required: false
    default: 'Status'
  page_property_type:
    description: 'The notion type of the property to update. Default is "status"'
    required: false
    default: 'status'
  on_pr:
    description: 'The value of page-property to be updated on PR event. Default is "In review"'
    required: false
    default: 'In review'
  on_merge:
    description: 'The value of page-property to be updated on PR MERGE event. Default is "Done"'
    required: false
    default: 'Done'
runs:
  using: 'node16'
  main: 'dist/index.js'
